version: '3.4'

services:
  webapp:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: onmed-backend-container
    image: onmed-backend-image:latest
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - database
    ports:
      - 9090:80
      - 4343:443
    networks:
      - db_bridge

  database:
    build:
      context: .
      dockerfile: ./apps/postgres/Dockerfile
    container_name: onmed-database-container
    hostname: onmed-database-host
    image: onmed-database-image
    restart: always
    ports:
      - 5437:5432
    networks:
      - db_bridge

networks:
  db_bridge:
    driver: bridge
    